
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/content-chat-server/
    overwrite: true
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
  - object: scripts/
    pattern: "**/*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755

 - object: scripts/
        pattern: "**/*.sh"
        owner: ec2-user
        group: ec2-user
        mode: 755

hooks:
  
  InstallDependencies:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root