version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/content-chat-server/
    overwrite: true
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
  - object: scripts/applcation_start.sh
    pattern: "**/*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root