version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js version 18 ..."
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - . ~/.nvm/nvm.sh
      - nvm install 18
      - nvm use 18
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm test
  post_build:
    commands:
      - zip -r application.zip .
artifacts:
  files:
    - "**/*"
  discard-paths: yes